import { ToolDefinition } from '../types';

export const ALL_TOOLS: ToolDefinition[] = [
  // ==================== CORE AI / AGENT ====================
  {
    id: 'versatile-agent',
    name: 'Versatile Execution Agent',
    category: 'ai',
    subcategory: 'Agent Orchestration',
    vietnameseDesc: 'Tác nhân thực thi đa năng tự động lập kế hoạch',
    description: 'Chains multiple tools, plans sub-tasks, and orchestrates full creative pipelines.',
    icon: 'Bot',
    status: 'available',
    badge: 'Pro Agent',
    tags: ['agent', 'orchestration', 'multi-step', 'automation'],
    requiredModel: 'gemini-3.7-flash',
  },
  {
    id: 'proactive-creator',
    name: 'Proactive Co-Creator',
    category: 'ai',
    subcategory: 'Creative Partner',
    vietnameseDesc: 'Đồng sáng tạo chủ động gợi ý phương án',
    description: 'Collaborates with you in real-time to suggest improvements, variations, and next moves.',
    icon: 'Sparkles',
    status: 'available',
    tags: ['creative', 'brainstorm', 'suggestions'],
    requiredModel: 'gemini-3.7-flash',
  },
  {
    id: 'function-kitchen',
    name: 'Function Call Kitchen',
    category: 'ai',
    subcategory: 'Developer / API',
    vietnameseDesc: 'Bếp điều phối gọi hàm AI và kiểm thử công cụ',
    description: 'Inspect schemas, trigger manual function calls, and verify structured JSON outputs.',
    icon: 'Cpu',
    status: 'available',
    tags: ['tools', 'developer', 'json', 'schema'],
    requiredModel: 'gemini-3.7-flash',
  },
  {
    id: 'native-audio-call',
    name: 'Native Audio Function Call',
    category: 'ai',
    subcategory: 'Voice Agent',
    vietnameseDesc: 'Gọi hàm âm thanh thời gian thực qua giọng nói',
    description: 'Interact with tools natively via live speech streams and direct tool dispatch.',
    icon: 'Mic',
    status: 'available',
    badge: 'Live',
    tags: ['live', 'voice', 'audio', 'realtime'],
    requiredModel: 'gemini-3.1-flash-live-preview',
  },
  {
    id: 'agentic-vision',
    name: 'Gemini Agentic Vision',
    category: 'ai',
    subcategory: 'Multimodal Vision',
    vietnameseDesc: 'Thị giác tác nhân phân tích đối tượng & tọa độ',
    description: 'Pinpoints visual elements, provides coordinates, and reasons across multi-image contexts.',
    icon: 'Eye',
    status: 'available',
    tags: ['vision', 'detection', 'bounding-box', 'spatial'],
    requiredModel: 'gemini-3.7-flash',
  },

  // ==================== IMAGE ====================
  {
    id: 'nano-banana',
    name: 'Nano Banana Studio',
    category: 'image',
    subcategory: 'Image Generation',
    vietnameseDesc: 'Chỉnh sửa và tạo hình nghệ thuật bằng AI',
    description: 'Generate high-fidelity visual assets, style transformations, and conceptual renders.',
    icon: 'Image',
    status: 'available',
    badge: 'Popular',
    tags: ['generate', 'art', 'concept', 'nano-banana'],
    requiredModel: 'gemini-3.1-flash-lite-image',
  },
  {
    id: 'pixshop',
    name: 'Pixshop',
    category: 'image',
    subcategory: 'Image Editing',
    vietnameseDesc: 'Chỉnh sửa ảnh chuyên nghiệp, xóa nền & bộ lọc',
    description: 'Background removal, canvas adjustments, smart color grading, and object inpainting.',
    icon: 'Sliders',
    status: 'available',
    tags: ['editing', 'remove-bg', 'filters', 'canvas'],
  },
  {
    id: 'product-mockup',
    name: 'Product Mockup Visualization',
    category: 'image',
    subcategory: 'Product',
    vietnameseDesc: 'Mô phỏng phối cảnh sản phẩm chuyên nghiệp',
    description: 'Render products into luxury studios, outdoor environments, and Amazon/E-commerce packshots.',
    icon: 'Box',
    status: 'available',
    tags: ['ecommerce', 'mockup', 'packaging', 'commercial'],
  },
  {
    id: 'enhance',
    name: 'ENHANCE! Image Upscaler',
    category: 'image',
    subcategory: 'Image Enhancement',
    vietnameseDesc: 'Nâng cấp chi tiết & độ sắc nét bằng AI đa tỷ lệ',
    description: 'AI-powered image enhancement and upscaling across 2x, 4x, and 8x factor presets.',
    icon: 'Zap',
    status: 'available',
    badge: 'AI Upscaler',
    tags: ['upscale', 'enhance', 'clarity', 'denoise'],
    requiredModel: 'gemini-3.1-flash-lite-image',
  },
  {
    id: 'ai-pointer-create',
    name: 'AI-Pointer Create',
    category: 'image',
    subcategory: 'Image Editing',
    vietnameseDesc: 'Chỉ điểm tạo chi tiết mới trên vùng chọn',
    description: 'Point or tap on a coordinate to seamlessly synthesize new objects or elements into place.',
    icon: 'MousePointerClick',
    status: 'available',
    tags: ['inpaint', 'pointer', 'localize', 'insert'],
  },
  {
    id: 'ai-pointer-find',
    name: 'AI-Pointer Find',
    category: 'image',
    subcategory: 'Image Understanding',
    vietnameseDesc: 'Chỉ điểm tìm kiếm đối tượng & đếm số lượng',
    description: 'Locate, segment, and extract specific items, patterns, or anomalies from uploaded media.',
    icon: 'Search',
    status: 'available',
    tags: ['detect', 'count', 'segment', 'find'],
  },
  {
    id: 'vibecheck',
    name: 'VibeCheck',
    category: 'image',
    subcategory: 'Prompt Testing',
    vietnameseDesc: 'Kiểm tra sắc thái & tối ưu prompt tạo hình',
    description: 'Test prompts across lighting, cinematic mood, color palettes, and stylistic variations.',
    icon: 'SmilePlus',
    status: 'available',
    tags: ['vibe', 'mood', 'prompt-matrix', 'style'],
  },

  // ==================== VIDEO ====================
  {
    id: 'veo-studio',
    name: 'Veo Studio',
    category: 'video',
    subcategory: 'Generate',
    vietnameseDesc: 'Tạo video điện ảnh từ mô tả văn bản & kịch bản',
    description: 'High-definition video generation with cinematography camera angles and scene consistency.',
    icon: 'Video',
    status: 'available',
    badge: 'Veo',
    tags: ['video', 'veo', 'cinematic', 'storyboard'],
    requiredModel: 'veo-3.1-lite-generate-preview',
  },
  {
    id: 'type-motion',
    name: 'Type Motion',
    category: 'video',
    subcategory: 'Generate',
    vietnameseDesc: 'Hiệu ứng chuyển động chữ nghệ thuật & kinetic',
    description: 'Generate dynamic animated typography and kinetic text sequences for video intros.',
    icon: 'Type',
    status: 'available',
    tags: ['typography', 'kinetic', 'title', 'motion'],
  },
  {
    id: 'bananimate',
    name: 'Bananimate',
    category: 'video',
    subcategory: 'Generate',
    vietnameseDesc: 'Hoạt hình hoá nhân vật & đối tượng từ ảnh tĩnh',
    description: 'Turn static character sketches and illustrations into animated video sequences.',
    icon: 'PlayCircle',
    status: 'available',
    tags: ['animation', 'cartoon', 'character', 'motion'],
  },
  {
    id: 'omni-product-studio',
    name: 'Omni Product Video Studio',
    category: 'video',
    subcategory: 'Product Video',
    vietnameseDesc: 'Studio dựng video thương mại sản phẩm 360',
    description: 'Generate 360-degree rotation reels, feature highlights, and commercial video assets.',
    icon: 'Layers',
    status: 'available',
    tags: ['commercial', '360', 'product-video', 'ad'],
  },
  {
    id: 'video-analyzer',
    name: 'Video Scene Analyzer',
    category: 'video',
    subcategory: 'Analyze',
    vietnameseDesc: 'Phân tích cảnh quay & bóc tách nội dung video',
    description: 'Deep scene breakdown, timestamps, keyframe extraction, and visual narration of video files.',
    icon: 'Film',
    status: 'available',
    tags: ['analyzer', 'keyframes', 'timestamps', 'video-ai'],
  },

  // ==================== AUDIO ====================
  {
    id: 'echoscript',
    name: 'EchoScript',
    category: 'audio',
    subcategory: 'Transcription',
    vietnameseDesc: 'Chuyển audio thành transcript có người nói',
    description: 'Multi-speaker diarized audio transcription with timestamps, sentiments, and language auto-detect.',
    icon: 'FileAudio',
    status: 'available',
    badge: 'Diarization',
    tags: ['transcript', 'speaker', 'timestamps', 'meeting'],
    requiredModel: 'gemini-3.5-transcribe',
  },
  {
    id: 'live-transcription',
    name: 'Side by Side Live Transcription',
    category: 'audio',
    subcategory: 'Transcription',
    vietnameseDesc: 'Chép lời trực tiếp song song với bản dịch',
    description: 'Real-time dual-pane live audio transcription alongside instant bilingual translations.',
    icon: 'SplitSquareVertical',
    status: 'available',
    tags: ['live', 'dual-pane', 'realtime', 'subtitles'],
  },
  {
    id: 'voice-library',
    name: 'Voice Library & TTS',
    category: 'audio',
    subcategory: 'Voice',
    vietnameseDesc: 'Thư viện giọng đọc AI đa ngôn ngữ & sắc thái',
    description: 'Expressive neural text-to-speech with natural cadence, multi-speaker dialogues, and tone control.',
    icon: 'Volume2',
    status: 'available',
    tags: ['tts', 'voice', 'speech', 'narration'],
    requiredModel: 'gemini-3.1-flash-tts-preview',
  },
  {
    id: 'world-radio',
    name: 'World Radio Translator',
    category: 'audio',
    subcategory: 'Translation',
    vietnameseDesc: 'Dịch phát thanh & âm thanh quốc tế sang tiếng Khmer',
    description: 'Listen to foreign broadcasts or audio recordings translated live into Khmer and English.',
    icon: 'Radio',
    status: 'available',
    tags: ['radio', 'broadcast', 'translation', 'global'],
  },
  {
    id: 'lyria-studio',
    name: 'Lyria Music Studio',
    category: 'audio',
    subcategory: 'Music',
    vietnameseDesc: 'Sáng tác giai điệu & âm nhạc AI theo phong cách',
    description: 'AI music composition studio supporting classical Khmer instruments (Roneat, Tro) and modern genres.',
    icon: 'Music',
    status: 'available',
    badge: 'Lyria',
    tags: ['music', 'synth', 'melody', 'instruments'],
    requiredModel: 'lyria-3-clip-preview',
  },

  // ==================== DOCUMENTS / KNOWLEDGE ====================
  {
    id: 'chat-docs',
    name: 'Chat with Docs',
    category: 'documents',
    subcategory: 'Document Chat',
    vietnameseDesc: 'Trò chuyện & hỏi đáp thông minh với tài liệu',
    description: 'Extract insights, summarize chapters, and ask deep questions across uploaded PDF/TXT/MD files.',
    icon: 'FileText',
    status: 'available',
    tags: ['pdf', 'rag', 'summary', 'research'],
  },
  {
    id: 'ask-manual',
    name: 'Ask the Manual',
    category: 'documents',
    subcategory: 'Document Chat',
    vietnameseDesc: 'Tra cứu sổ tay kỹ thuật & hướng dẫn sử dụng',
    description: 'Specialized step-by-step diagnostic and procedural assistant for technical manuals and blueprints.',
    icon: 'BookOpen',
    status: 'available',
    tags: ['manual', 'troubleshooting', 'specs', 'guide'],
  },
  {
    id: 'multimodal-search',
    name: 'Multimodal Search Engine',
    category: 'documents',
    subcategory: 'Search',
    vietnameseDesc: 'Tìm kiếm đa phương thức kết hợp văn bản & hình ảnh',
    description: 'Semantic vector search across your files, sketches, and notes using multimodal context.',
    icon: 'SearchCheck',
    status: 'available',
    tags: ['search', 'semantic', 'cross-modal', 'files'],
  },
  {
    id: 'infinite-wiki',
    name: 'Infinite Wiki',
    category: 'documents',
    subcategory: 'Knowledge',
    vietnameseDesc: 'Bách khoa toàn thư tri thức tự động mở rộng',
    description: 'Explore deeply linked, interactive encyclopedic knowledge graphs with auto-generated subpages.',
    icon: 'Globe',
    status: 'available',
    badge: 'Knowledge Graph',
    tags: ['wiki', 'encyclopedia', 'graph', 'deep-dive'],
  },
  {
    id: 'embeddings-visualizer',
    name: 'Embeddings Inspector',
    category: 'documents',
    subcategory: 'Search',
    vietnameseDesc: 'Trực quan hoá không gian vector & mức độ tương đồng',
    description: 'Inspect 2D/3D topological semantic clusters and cosine distance between documents and ideas.',
    icon: 'Network',
    status: 'available',
    tags: ['vectors', 'embeddings', 'similarity', 'clusters'],
    requiredModel: 'gemini-embedding-2-preview',
  },

  // ==================== LEARNING ====================
  {
    id: 'intute',
    name: 'InTute AI Tutor',
    category: 'learning',
    subcategory: 'AI Tutor',
    vietnameseDesc: 'Gia sư AI tương tác từng bước theo phương pháp Socratic',
    description: 'Personalized interactive tutoring that guides you with thoughtful questions, diagrams, and proofs.',
    icon: 'GraduationCap',
    status: 'available',
    badge: 'Socratic',
    tags: ['tutor', 'socratic', 'education', 'stem'],
  },
  {
    id: 'flashcard-maker',
    name: 'Smart Flashcard Maker',
    category: 'learning',
    subcategory: 'Flashcards',
    vietnameseDesc: 'Tạo thẻ ghi nhớ thông minh lặp lại ngắt quãng (SRS)',
    description: 'Spaced repetition flashcard engine with bilingual Khmer-English-Vietnamese decks and audio cues.',
    icon: 'GalleryVerticalEnd',
    status: 'available',
    tags: ['flashcards', 'srs', 'memorize', 'quiz'],
  },
  {
    id: 'visual-dict',
    name: 'Interactive Visual Dictionary',
    category: 'learning',
    subcategory: 'Visual Dictionary',
    vietnameseDesc: 'Từ điển trực quan tương tác hình ảnh & phát âm',
    description: 'Clickable photographic scenes and schematics with labeled anatomy, terms, and audio pronunciation.',
    icon: 'Compass',
    status: 'available',
    tags: ['visual-dictionary', 'anatomy', 'clickable', 'vocabulary'],
  },
  {
    id: 'video-learning',
    name: 'Video to Learning App',
    category: 'learning',
    subcategory: 'Video Learning',
    vietnameseDesc: 'Biến video thành bài giảng tương tác & trắc nghiệm',
    description: 'Convert lectures, documentaries, and tutorials into structured study guides, flashcards, and quizzes.',
    icon: 'Tv',
    status: 'available',
    tags: ['video-learning', 'quizzes', 'study-guide', 'notes'],
  },

  // ==================== KHMER WORKSPACE ====================
  {
    id: 'khmer-lang',
    name: 'Khmer Language Specialist',
    category: 'khmer',
    subcategory: 'Khmer Language',
    vietnameseDesc: 'Kiểm tra ngữ pháp & chính tả chuẩn tiếng Khmer',
    description: 'Grammar analysis, subscript consonant validation (ជើង), word segmentation, and stylistic polish.',
    icon: 'Feather',
    status: 'available',
    badge: 'ភាសាខ្មែរ',
    tags: ['khmer', 'grammar', 'orthography', 'spelling'],
  },
  {
    id: 'khmer-dict',
    name: 'Chuon Nath Digital Lexicon',
    category: 'khmer',
    subcategory: 'Khmer Dictionary',
    vietnameseDesc: 'Từ điển Chuon Nath & tra cứu từ ngữ chuyên sâu',
    description: 'Comprehensive definitions from Samdach Sangha Chuon Nath dictionary with modern etymology and audio.',
    icon: 'BookMarked',
    status: 'available',
    tags: ['chuon-nath', 'dictionary', 'etymology', 'pali-sanskrit'],
  },
  {
    id: 'khmer-learn',
    name: 'Khmer Script & Calligraphy Tutor',
    category: 'khmer',
    subcategory: 'Khmer Learning',
    vietnameseDesc: 'Luyện chữ viết, 33 phụ âm & nguyên âm tiếng Khmer',
    description: 'Interactive stroke order, O-series & O-series consonant groups, independent vowels, and phonetics.',
    icon: 'PenTool',
    status: 'available',
    tags: ['alphabet', 'consonants', 'calligraphy', 'phonetics'],
  },
  {
    id: 'khmer-ocr',
    name: 'Khmer Epigraphy & Script OCR',
    category: 'khmer',
    subcategory: 'Khmer OCR',
    vietnameseDesc: 'Trích xuất chữ khắc cổ Angkor & chữ in từ hình ảnh',
    description: 'High-accuracy OCR for contemporary Khmer typography, temple stone inscriptions, and historical manuscripts.',
    icon: 'ScanText',
    status: 'available',
    tags: ['ocr', 'inscriptions', 'angkor', 'script-reader'],
  },
  {
    id: 'khmer-translate',
    name: 'Khmer Multi-Register Translator',
    category: 'khmer',
    subcategory: 'Khmer Translation',
    vietnameseDesc: 'Dịch thuật chuẩn xác đa kính ngữ Khmer - Anh - Việt',
    description: 'Culturally nuanced translation honoring formal, casual, Buddhist monk, and royal registers (រាជសព្ទ).',
    icon: 'Languages',
    status: 'available',
    tags: ['translator', 'royal-register', 'bilingual', 'contextual'],
  },
  {
    id: 'khmer-heritage',
    name: 'Angkor Heritage & Classical Arts',
    category: 'khmer',
    subcategory: 'Khmer Heritage',
    vietnameseDesc: 'Khám phá di sản Angkor, Apsara & nghệ thuật Khmer',
    description: 'Interactive architectural models of Angkor Wat, Bayon, classical Apsara dance gestures, and Sbek Thom.',
    icon: 'Landmark',
    status: 'available',
    tags: ['angkor', 'apsara', 'history', 'monuments'],
  },
  {
    id: 'khmer-content',
    name: 'Khmer Creative Content Studio',
    category: 'khmer',
    subcategory: 'Khmer Content',
    vietnameseDesc: 'Sáng tạo nội dung truyền thông & thư từ chữ Khmer',
    description: 'Draft formal administrative letters, poetry (Kbach Khmer), social media captions, and video scripts.',
    icon: 'Palette',
    status: 'available',
    tags: ['content', 'poetry', 'formal-letter', 'social'],
  },
  {
    id: 'khmer-speech-engine',
    name: 'Khmer Neural Voice Synthesis',
    category: 'khmer',
    subcategory: 'Khmer Speech',
    vietnameseDesc: 'Công nghệ giọng đọc Khmer tự nhiên (Hạ tầng)',
    description: 'Dedicated Khmer neural speech engine status and synthesis interface.',
    icon: 'AudioLines',
    status: 'requires_api',
    badge: 'API Setup',
    tags: ['speech-synthesis', 'tts-khmer', 'phonetics'],
  },

  // ==================== AUTOMATION ====================
  {
    id: 'visual-builder',
    name: 'Visual Workflow Builder',
    category: 'automation',
    subcategory: 'Workflows',
    vietnameseDesc: 'Xây dựng quy trình tự động hoá đa tác vụ nối tiếp',
    description: 'Visually connect input assets, AI agent steps, filters, upscalers, and export formats.',
    icon: 'Workflow',
    status: 'available',
    badge: 'Visual Node',
    tags: ['workflow', 'nodes', 'pipeline', 'batch'],
  },
  {
    id: 'ai-workflow-gen',
    name: 'AI Prompt-to-Workflow',
    category: 'automation',
    subcategory: 'AI Generator',
    vietnameseDesc: 'Tạo quy trình tự động hoá từ câu lệnh tự nhiên',
    description: 'Describe an objective like "Turn photos into e-commerce catalog" and auto-construct the pipeline.',
    icon: 'Wand2',
    status: 'available',
    tags: ['auto-pipeline', 'smart-builder', 'preset'],
  },
];
