import { KhmerAlphabetItem, FlashcardItem } from '../types';

export const KHMER_CONSONANTS: KhmerAlphabetItem[] = [
  // 33 Consonants grouped by Series
  { char: 'ក', name: 'Kâ', ipa: '/kɑː/', series: 'first', meaning: 'Chicken (មាន់/ក)', exampleWord: 'ក្អែក', exampleMeaning: 'Crow' },
  { char: 'ខ', name: 'Khâ', ipa: '/kʰɑː/', series: 'first', meaning: 'Pillow / Step', exampleWord: 'ខ្លា', exampleMeaning: 'Tiger' },
  { char: 'គ', name: 'Kô', ipa: '/koː/', series: 'second', meaning: 'Ox / Cow', exampleWord: 'គោ', exampleMeaning: 'Ox' },
  { char: 'ឃ', name: 'Khô', ipa: '/kʰoː/', series: 'second', meaning: 'Bell / Clock', exampleWord: 'ឃ្មុំ', exampleMeaning: 'Bee' },
  { char: 'ង', name: 'Ngô', ipa: '/ŋoː/', series: 'second', meaning: 'Squid / Sesame', exampleWord: 'ងងឹត', exampleMeaning: 'Dark' },

  { char: 'ច', name: 'Châ', ipa: '/cɑː/', series: 'first', meaning: 'Banana comb', exampleWord: 'ចាប', exampleMeaning: 'Sparrow' },
  { char: 'ឆ', name: 'Chhâ', ipa: '/cʰɑː/', series: 'first', meaning: 'Parasol / Umbrella', exampleWord: 'ឆ្មា', exampleMeaning: 'Cat' },
  { char: 'ជ', name: 'Chô', ipa: '/coː/', series: 'second', meaning: 'Leg / Foot', exampleWord: 'ជើង', exampleMeaning: 'Foot' },
  { char: 'ឈ', name: 'Chhô', ipa: '/cʰoː/', series: 'second', meaning: 'Tree / Wood', exampleWord: 'ឈើ', exampleMeaning: 'Wood' },
  { char: 'ញ', name: 'Nhô', ipa: '/ɲoː/', series: 'second', meaning: 'Face / Smile', exampleWord: 'ញញឹម', exampleMeaning: 'Smile' },

  { char: 'ដ', name: 'Dâ', ipa: '/ɗɑː/', series: 'first', meaning: 'Plant / Yam', exampleWord: 'ដំរី', exampleMeaning: 'Elephant' },
  { char: 'ឋ', name: 'Thâ', ipa: '/tʰɑː/', series: 'first', meaning: 'Base / Place', exampleWord: 'ឋាន', exampleMeaning: 'Realm' },
  { char: 'ឌ', name: 'Dô', ipa: '/ɗoː/', series: 'second', meaning: 'Island / Big spoon', exampleWord: 'ឌុក', exampleMeaning: 'Duk sound' },
  { char: 'ឍ', name: 'Thô', ipa: '/tʰoː/', series: 'second', meaning: 'Old age', exampleWord: 'ឍាមរា', exampleMeaning: 'Aged person' },
  { char: 'ណ', name: 'Nâ', ipa: '/nɑː/', series: 'first', meaning: 'Direction', exampleWord: 'ណែនាំ', exampleMeaning: 'Guide' },

  { char: 'ត', name: 'Tâ', ipa: '/tɑː/', series: 'first', meaning: 'Grandfather / Join', exampleWord: 'ត្រី', exampleMeaning: 'Fish' },
  { char: 'ថ', name: 'Thâ', ipa: '/tʰɑː/', series: 'first', meaning: 'Tray / Bag', exampleWord: 'ថង់', exampleMeaning: 'Bag' },
  { char: 'ទ', name: 'Tô', ipa: '/toː/', series: 'second', meaning: 'Boat / Duck', exampleWord: 'ទា', exampleMeaning: 'Duck' },
  { char: 'ធ', name: 'Thô', ipa: '/tʰoː/', series: 'second', meaning: 'Big / Large', exampleWord: 'ធំ', exampleMeaning: 'Big' },
  { char: 'ន', name: 'Nô', ipa: '/noː/', series: 'second', meaning: 'Bird / Boatman', exampleWord: 'នាគ', exampleMeaning: 'Naga' },

  { char: 'ប', name: 'Bâ', ipa: '/ɓɑː/', series: 'first', meaning: 'Leaf / Plate', exampleWord: 'បាយ', exampleMeaning: 'Rice / Meal' },
  { char: 'ផ', name: 'Phâ', ipa: '/pʰɑː/', series: 'first', meaning: 'Flower / Fruit', exampleWord: 'ផ្កា', exampleMeaning: 'Flower' },
  { char: 'ព', name: 'Pô', ipa: '/poː/', series: 'second', meaning: 'Goat / Snake', exampleWord: 'ពពក', exampleMeaning: 'Cloud' },
  { char: 'ភ', name: 'Phô', ipa: '/pʰoː/', series: 'second', meaning: 'Mountain / Village', exampleWord: 'ភ្នំ', exampleMeaning: 'Mountain' },
  { char: 'ម', name: 'Mô', ipa: '/moː/', series: 'second', meaning: 'Gold / Chicken', exampleWord: 'មាស', exampleMeaning: 'Gold' },

  { char: 'យ', name: 'Yô', ipa: '/joː/', series: 'second', meaning: 'Giant / Demon', exampleWord: 'យក្ស', exampleMeaning: 'Giant' },
  { char: 'រ', name: 'Rô', ipa: '/roː/', series: 'second', meaning: 'Car / Cart', exampleWord: 'រថយន្ត', exampleMeaning: 'Car' },
  { char: 'ល', name: 'Lô', ipa: '/loː/', series: 'second', meaning: 'Monkey / Silver', exampleWord: 'លុយ', exampleMeaning: 'Money' },
  { char: 'វ', name: 'Vô', ipa: '/ʋoː/', series: 'second', meaning: 'Palace / Temple', exampleWord: 'វត្ត', exampleMeaning: 'Pagoda / Wat' },
  { char: 'ស', name: 'Sâ', ipa: '/sɑː/', series: 'first', meaning: 'White / Hair', exampleWord: 'សៀវភៅ', exampleMeaning: 'Book' },
  { char: 'ហ', name: 'Hâ', ipa: '/hɑː/', series: 'first', meaning: 'Swan / Chest', exampleWord: 'ហង្ស', exampleMeaning: 'Hamsa / Swan' },
  { char: 'ឡ', name: 'Lâ', ipa: '/lɑː/', series: 'first', meaning: 'Cart / Mule', exampleWord: 'ឡាន', exampleMeaning: 'Automobile' },
  { char: 'អ', name: 'Â', ipa: '/ʔɑː/', series: 'first', meaning: 'Self / Father', exampleWord: 'អង្ករ', exampleMeaning: 'Uncooked rice' },
];

export const KHMER_VOWELS: KhmerAlphabetItem[] = [
  { char: 'ា', name: 'Sra Ah', ipa: '/aː/ or /iə/', series: 'vowel', meaning: 'Dependent vowel A' },
  { char: 'ិ', name: 'Sra E', ipa: '/ə/ or /i/', series: 'vowel', meaning: 'Dependent vowel I' },
  { char: 'ី', name: 'Sra Ey', ipa: '/əj/ or /iː/', series: 'vowel', meaning: 'Dependent vowel II' },
  { char: 'ឹ', name: 'Sra Ue', ipa: '/ə/ or /ɨ/', series: 'vowel', meaning: 'Dependent vowel Y' },
  { char: 'ឺ', name: 'Sra Uee', ipa: '/əɨ/ or /ɨː/', series: 'vowel', meaning: 'Dependent vowel YY' },
  { char: 'ុ', name: 'Sra O', ipa: '/o/ or /u/', series: 'vowel', meaning: 'Dependent vowel U' },
  { char: 'ូ', name: 'Sra Oo', ipa: '/ou/ or /uː/', series: 'vowel', meaning: 'Dependent vowel UU' },
  { char: 'ួ', name: 'Sra Uo', ipa: '/uə/', series: 'vowel', meaning: 'Dependent vowel UA' },
  { char: 'ើ', name: 'Sra Aeu', ipa: '/aə/ or /əː/', series: 'vowel', meaning: 'Dependent vowel OE' },
  { char: 'ឿ', name: 'Sra Iea', ipa: '/ɨə/', series: 'vowel', meaning: 'Dependent vowel YA' },
  { char: 'ៀ', name: 'Sra Eea', ipa: '/iə/', series: 'vowel', meaning: 'Dependent vowel IE' },
  { char: 'េ', name: 'Sra Ae', ipa: '/eː/ or /eː/', series: 'vowel', meaning: 'Dependent vowel E' },
  { char: 'ែ', name: 'Sra Ae', ipa: '/ae/ or /ɛː/', series: 'vowel', meaning: 'Dependent vowel AE' },
  { char: 'ៃ', name: 'Sra Ay', ipa: '/aj/ or /ɨj/', series: 'vowel', meaning: 'Dependent vowel AI' },
  { char: 'ោ', name: 'Sra Ao', ipa: '/ao/ or /oː/', series: 'vowel', meaning: 'Dependent vowel OO' },
  { char: 'ៅ', name: 'Sra Aw', ipa: '/aw/ or /ɨw/', series: 'vowel', meaning: 'Dependent vowel AU' },
];

export const INITIAL_FLASHCARDS: FlashcardItem[] = [
  {
    id: 'fc-1',
    khmer: 'សួស្តី',
    ipa: 'suos-dey',
    english: 'Hello / Greetings',
    vietnamese: 'Xin chào',
    partOfSpeech: 'Interjection',
    exampleKhmer: 'សួស្តី! តើអ្នកសុខសប្បាយជាទេ?',
    exampleEnglish: 'Hello! How are you doing?',
    category: 'Greetings',
    masteryLevel: 4,
  },
  {
    id: 'fc-2',
    khmer: 'អរគុណ',
    ipa: 'or-kun',
    english: 'Thank you',
    vietnamese: 'Cảm ơn',
    partOfSpeech: 'Expression',
    exampleKhmer: 'អរគុណច្រើនសម្រាប់ការជួយរបស់អ្នក។',
    exampleEnglish: 'Thank you very much for your help.',
    category: 'Courtesies',
    masteryLevel: 5,
  },
  {
    id: 'fc-3',
    khmer: 'ប្រាសាទអង្គរវត្ត',
    ipa: 'prasat angkor wat',
    english: 'Angkor Wat Temple',
    vietnamese: 'Đền Angkor Wat',
    partOfSpeech: 'Proper Noun',
    exampleKhmer: 'ប្រាសាទអង្គរវត្តជាបេតិកភណ្ឌពិភពលោក។',
    exampleEnglish: 'Angkor Wat is a World Heritage site.',
    category: 'Culture & Heritage',
    masteryLevel: 3,
  },
  {
    id: 'fc-4',
    khmer: 'បញ្ញាសិប្បនិម្មិត',
    ipa: 'panya seip-ni-met',
    english: 'Artificial Intelligence (AI)',
    vietnamese: 'Trí tuệ nhân tạo (AI)',
    partOfSpeech: 'Noun',
    exampleKhmer: 'បញ្ញាសិប្បនិម្មិតកំពុងផ្លាស់ប្តូរពិភពលោក។',
    exampleEnglish: 'Artificial intelligence is transforming the world.',
    category: 'Technology',
    masteryLevel: 2,
  },
  {
    id: 'fc-5',
    khmer: 'របាំអប្សរា',
    ipa: 'robam apsara',
    english: 'Apsara Classical Dance',
    vietnamese: 'Điệu múa Apsara',
    partOfSpeech: 'Noun',
    exampleKhmer: 'របាំអប្សរាបង្ហាញពីភាពទន់ភ្លន់និងរស់រវើក។',
    exampleEnglish: 'The Apsara dance exhibits grace and vibrancy.',
    category: 'Culture & Heritage',
    masteryLevel: 4,
  },
  {
    id: 'fc-6',
    khmer: 'សន្តិភាព',
    ipa: 'santi-pheap',
    english: 'Peace / Tranquility',
    vietnamese: 'Hòa bình',
    partOfSpeech: 'Noun',
    exampleKhmer: 'យើងស្រឡាញ់សន្តិភាពនិងមិត្តភាព។',
    exampleEnglish: 'We love peace and friendship.',
    category: 'Philosophy',
    masteryLevel: 3,
  },
];

export const KHMER_FLASHCARDS = INITIAL_FLASHCARDS.map((f) => ({
  id: f.id,
  front: f.khmer,
  back: f.english,
  pronunciation: f.ipa,
  category: f.category,
  notes: `${f.vietnamese} • Example: ${f.exampleKhmer} (${f.exampleEnglish})`,
}));

export const HERITAGE_TOPICS = [
  {
    id: 'angkor-wat',
    title: 'Angkor Wat (អង្គរវត្ត)',
    period: 'Early 12th Century (Suryavarman II)',
    category: 'Architecture',
    summary: 'The largest religious monument in the world, originally constructed as a Hindu temple dedicated to Vishnu before transforming into a Buddhist temple.',
    architecturalHighlights: [
      'Towering central quincunx representing Mount Meru',
      '800-meter outer gallery with bas-reliefs depicting the Churning of the Ocean of Milk',
      'Precise solar equinox alignments where sun rises directly above central tower',
    ],
    symbolism: 'Cosmic microcosm, moat representing the cosmic ocean.',
  },
  {
    id: 'bayon',
    title: 'The Bayon (ប្រាសាទបាយ័ន)',
    period: 'Late 12th / Early 13th Century (Jayavarman VII)',
    category: 'Architecture & Sculpture',
    summary: 'The mesmerizing state temple of King Jayavarman VII at Angkor Thom, famous for 216 serene smiling stone faces.',
    architecturalHighlights: [
      '54 towers bearing four gigantic smiling face carvings of Avalokiteshvara/Lokeshvara',
      'Vivid outer bas-reliefs recording everyday 12th-century Khmer market life, battles, and festivals',
      'Circular central sanctuary representing Buddhist cosmic mandala',
    ],
    symbolism: 'All-seeing compassionate gaze (Karuna) overlooking the Khmer empire.',
  },
  {
    id: 'apsara-dance',
    title: 'Robam Tep Apsara (របាំទេពអប្សរា)',
    period: 'Angkorian Classical Tradition / Royal Ballet of Cambodia',
    category: 'Classical Arts',
    summary: 'Sacred classical dance representing celestial water nymphs who bring divine blessings of fertility, rainfall, and cosmic balance.',
    architecturalHighlights: [
      'Over 4,500 distinct hand gestures (Kbach / ជីព) symbolizing lotus buds, fruit, flowers, and leaves',
      'Elaborate gilded Mokot (crowns) and silk sampot chong kben',
      'Accompanied by the sacred Pinpeat orchestra (Roneat, Sralai, Samphor, Kong Vong)',
    ],
    symbolism: 'Sacred conduit between the divine pantheon and mortal prosperity.',
  },
  {
    id: 'sbek-thom',
    title: 'Sbek Thom Shadow Theatre (ល្ខោនស្បែកធំ)',
    period: 'Pre-Angkorian / Angkorian Era',
    category: 'Performing Heritage',
    summary: 'UNESCO Intangible Cultural Heritage sacred shadow puppet performance portraying epic episodes of the Reamker (Khmer Ramayana).',
    architecturalHighlights: [
      'Non-articulated large leather puppets carved from single cowhides dyed with tree bark',
      'Fire-lit torch screen performance accompanied by ritual narration and Pinpeat percussion',
      'Performed traditionally during Khmer New Year and royal coronations',
    ],
    symbolism: 'Spiritual invocation and moral allegories of dharma triumphing over chaos.',
  },
];

export const KHMER_HERITAGE_TOPICS = HERITAGE_TOPICS;

